# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
  name: Setup Go environment
  uses: actions/setup-go@v4.0.0
  with:
    # The Go version to download (if necessary) and use. Supports semver spec and ranges.
    go-version: # optional
    # Path to the go.mod or go.work file.
    go-version-file: # optional
    # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
    check-latest: # optional
    # Used to pull node distributions from go-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
    cache: # optional, default is true
    # Used to specify the path to a dependency file - go.sum
    cache-dependency-path: # optional
    # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
    architecture: # optional
  name: variable-mapper
  # You may pin to the exact commit or the version.
  # uses: kanga333/variable-mapper@3681b75f5c6c00162721168fb91ab74925eaebcb
  uses: kanga333/variable-mapper@v0.3.0
  with:
    # Key to match the map argument
    key: # optional
    # Pairs of regular expressions and variables
    map: # optional, default is 
    # Comma-separated list of targets to export variables to. log, env and output are valid values.
    export_to: # optional, default is log,env
    # Specify the behavior of getting the variable. first_match, overwrite and fill are valid values.
    mode: # optional, default is first_match
  name: Variable mapper action
  # You may pin to the exact commit or the version.
  # uses: chris-madsen/variable-mapper@86e3bf612d72e9366b01e8709791fc7a7300a398
  uses: chris-madsen/variable-mapper@v0.1.3
  with:
    # Key to match the map argument
    key: # optional
    # Pairs of regular expressions and variables
    map: # optional, default is 
    # Comma-separated list of targets to export variables to. log, env and output are valid values.
    export_to: # optional, default is log,env
  name: Run Circle-CI on Label
  # You may pin to the exact commit or the version.
  # uses: Open-Source-Contrib/circle-ci-trigger-action@9b30ef8dfcbd75a5d4966debdb743ba7ce0bbe1d
  uses: Open-Source-Contrib/circle-ci-trigger-action@latest
  with:
    # Token for Circle-CI
    circle_ci_token: # default is 
    # Name of the circle-ci-job
    circle_ci_job: # default is 
    # URL for circle-ci project
    circle_ci_project_url: # default is 
